/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as protectedVideo_streamIndexRouteImport } from './routes/(protected)/video_stream/index'
import { Route as protectedProfileIndexRouteImport } from './routes/(protected)/profile/index'
import { Route as protectedDashboardIndexRouteImport } from './routes/(protected)/dashboard/index'
import { Route as protectedAddressIndexRouteImport } from './routes/(protected)/address/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedVideo_streamIndexRoute =
  protectedVideo_streamIndexRouteImport.update({
    id: '/video_stream/',
    path: '/video_stream/',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedProfileIndexRoute = protectedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedDashboardIndexRoute = protectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedAddressIndexRoute = protectedAddressIndexRouteImport.update({
  id: '/address/',
  path: '/address/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/address/': typeof protectedAddressIndexRoute
  '/dashboard/': typeof protectedDashboardIndexRoute
  '/profile/': typeof protectedProfileIndexRoute
  '/video_stream/': typeof protectedVideo_streamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/address': typeof protectedAddressIndexRoute
  '/dashboard': typeof protectedDashboardIndexRoute
  '/profile': typeof protectedProfileIndexRoute
  '/video_stream': typeof protectedVideo_streamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(protected)/address/': typeof protectedAddressIndexRoute
  '/(protected)/dashboard/': typeof protectedDashboardIndexRoute
  '/(protected)/profile/': typeof protectedProfileIndexRoute
  '/(protected)/video_stream/': typeof protectedVideo_streamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/auth/$'
    | '/address/'
    | '/dashboard/'
    | '/profile/'
    | '/video_stream/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/$'
    | '/address'
    | '/dashboard'
    | '/profile'
    | '/video_stream'
  id:
    | '__root__'
    | '/'
    | '/(protected)'
    | '/api/auth/$'
    | '/(protected)/address/'
    | '/(protected)/dashboard/'
    | '/(protected)/profile/'
    | '/(protected)/video_stream/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/video_stream/': {
      id: '/(protected)/video_stream/'
      path: '/video_stream'
      fullPath: '/video_stream/'
      preLoaderRoute: typeof protectedVideo_streamIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/profile/': {
      id: '/(protected)/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof protectedProfileIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/dashboard/': {
      id: '/(protected)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof protectedDashboardIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/address/': {
      id: '/(protected)/address/'
      path: '/address'
      fullPath: '/address/'
      preLoaderRoute: typeof protectedAddressIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface protectedRouteRouteChildren {
  protectedAddressIndexRoute: typeof protectedAddressIndexRoute
  protectedDashboardIndexRoute: typeof protectedDashboardIndexRoute
  protectedProfileIndexRoute: typeof protectedProfileIndexRoute
  protectedVideo_streamIndexRoute: typeof protectedVideo_streamIndexRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedAddressIndexRoute: protectedAddressIndexRoute,
  protectedDashboardIndexRoute: protectedDashboardIndexRoute,
  protectedProfileIndexRoute: protectedProfileIndexRoute,
  protectedVideo_streamIndexRoute: protectedVideo_streamIndexRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  protectedRouteRoute: protectedRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
